#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/vala-mode-el

FLAVOR=$1
PACKAGE=vala-mode-el

if [ ${FLAVOR} != emacs ]; then
    echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}
    rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
